spring:
   datasource:
     username: root
     password: 1234
     url: jdbc:mysql://localhost:3306/ssm?serverTimezone=Asia/Shanghai
     driver-class-name: com.mysql.cj.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classth:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
jackson:
   date-format: yyyy-MM-dd
